name: Deploy web

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'

jobs:
  deploy-web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install deps
        working-directory: ./web
        run: npm i

      - name: Deploy
        working-directory: ./web
        run: npm run deploy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
